source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LeeGo_Example', :exclusive => true do
  pod "LeeGo", :path => "../"
  
  pod 'ReactiveCocoa', '4.0.0-alpha-3'
end

target 'LeeGo_Tests', :exclusive => true do
  pod "LeeGo", :path => "../"

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
